"""initial

Revision ID: b18e15aba6a1
Revises: 
Create Date: 2026-01-13 15:55:39.139836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18e15aba6a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('start_investment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('end_proceeds', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('profit_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_histories_symbol'), 'cycle_histories', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('filled_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kiwoom_order_id', sa.String(length=50), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('split_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('symbol_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('splits_used', sa.Integer(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('current_investment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initial_investment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cycle_histories_symbol'), table_name='cycle_histories')
    op.drop_table('cycle_histories')
    # ### end Alembic commands ###
